name: Quantum Study Toolkit Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'quantum-study-toolkit/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'quantum-study-toolkit/**'

jobs:

  build-and-push-docker-image:
    name: Build Docker image and push to docker hub

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login | Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build image and push to Repositories
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./quantum-study-toolkit
        # Note: tags has to be all lower-case
        tags: |
          fullofentropy/quantum-study-toolkit:latest 
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


      # run: docker build . --file quantum-study-toolkit/Dockerfile --tag quantum-study-toolkit:$(date +%s)